[package]
name = "burn-extended"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Extended attention modules and utilities for Burn (MQA/GQA, sinks bias, RoPE NTK/YaRN), extracted as a separate crate for modular reuse."
repository = "https://github.com/tracel-ai/burn"
documentation = "https://docs.rs/burn-extended"
publish = false

[lints]
workspace = true

[dependencies]
# Point to antimora/burn commit that includes burn-store
burn-core   = { git = "https://github.com/antimora/burn", rev = "7235cf2f5cd501d2abc578865a592e6fb59d1772", package = "burn-core",   default-features = false }
burn-tensor = { git = "https://github.com/antimora/burn", rev = "7235cf2f5cd501d2abc578865a592e6fb59d1772", package = "burn-tensor", default-features = false }
burn-store  = { git = "https://github.com/antimora/burn", rev = "7235cf2f5cd501d2abc578865a592e6fb59d1772", package = "burn-store",  default-features = false, optional = true }
safetensors = { version = "0.4", default-features = true, optional = true }

[features]
default = ["std"]
std = ["burn-core/std"]
store = ["dep:burn-store", "dep:safetensors"]

[dev-dependencies]
winit = "0.29"
clap = { version = "4", features = ["derive"], default-features = true }
